### ISSUE TITLE
Windows 95: Menu strip font is not the correct font

### ISSUE THREAD

**Issue by jtsshieh** [LemonyStudios/Histacom2#186]
Look at the title ^^

**Comment by lempamo** [comment]
what do ya mean by "menu strip font"?

**Comment by jtsshieh** [comment]
Wait, lemme get a screenshot

**Comment by jtsshieh** [comment]
I think I meant at the time the start menu font

**Comment by lempamo** [comment]
well thats the correct font now sooo
